### ISSUE TITLE
Bold font

### ISSUE THREAD

**Issue by pablopunk** [henrikdahl/hyperterm-chesterish#7]
Just curious, what's the point of this line?

```css
span {
  font-weight: normal !important;
}
```

It's preventing my prompt for being bold, which I like.

Congrats for this awesome theme BTW!!
